services:
  app:
    build: .
    container_name: howhotisit
    ports:
      - "8080:8080"
    volumes:
      - ./temphistory.db:/app/data/temphistory.db
    restart: unless-stopped
    privileged: true
    environment:
      - FLASK_ENV=production
